"""Generated current-state page (GOV-05): `CURRENT_STATE.md`.

One page states what is true now - method, control revision, active manifest, next canonical ID, active Combined Log, mini format,
selection gates, scoreboard headline, runtime evidence and source status - computed from the repository, so no other document has to carry
a next ID or a destination. Other documents point here.

  python -B -m research.operations.current_state write     # regenerate CURRENT_STATE.md
  python -B -m research.operations.current_state verify    # fail when CURRENT_STATE.md differs from a fresh render, or a living document states a next ID
"""
from __future__ import annotations
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'CURRENT_STATE.md'
LIVING_DOCS = ('README.md', 'CURRENT_RULES.md', 'METHOD.md', 'research/README.md', 'runtime/README.md', 'CARD_AND_LOG_TEMPLATES.md', 'research/prompts/README.md')
# a living document may not state which ID is next or which log part is the destination; both change at every rollover
STALE = re.compile(r"(?i)\bnext (?:canonical )?(?:ID|card ID)\b[^.\n]{0,40}\bP-\d{3,}|\bP-\d{3,}\b[^.\n]{0,30}\b(?:remains|is|stays) (?:the )?next\b|\bnext ID (?:stays|is|remains)\b|"
                   r"\bsole canonical destination\b|\bis now active\b|\bis the active (?:combined )?log\b")


def _read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding='utf-8')


def _json(rel: str) -> dict:
    return json.loads(_read(rel))


def facts() -> dict:
    from research.operations.canonical_issue import next_card_id
    from research.src.combined_log import active_log
    method = _read('METHOD.md')
    status = re.search(r'Status: \*\*(\w+)\*\*\. Method \*\*([^*]+)\*\*\. Control revision \*\*([^*]+)\*\*\. Scoring \*\*([^*]+)\*\*\. Active freeze: \[([^\]]+)\]', method)
    if not status:
        raise ValueError('METHOD.md status line not found')
    board = _json('research/scoreboard/SCOREBOARD.json')
    rules = _json('runtime/config/selection_rules.json')
    pointer = _json('research/current_settlement_register.json')
    runtime = _json('research/model_builds/runtime_h0/INDEX.json')
    challenger = _json('research/model_builds/runtime_h0/challenger/INDEX.json')
    adapters = _json('research/sources_registry_adapters.json')['sources']
    registry = _json('research/sources_registry.json')['sources']
    audits = sorted(p.stem for p in (ROOT / 'research/lineage_audits').glob('*.json'))
    reach = sorted({json.loads(p.read_text(encoding='utf-8'))['environment'] for p in (ROOT / 'research/reachability').glob('*.json')})
    return {'status': status[1], 'method': status[2], 'control': status[3], 'scoring': status[4], 'manifest': status[5],
            'next_id': next_card_id(), 'log': active_log().name, 'board': board, 'rules': rules, 'pointer': pointer, 'runtime': runtime,
            'challenger': challenger, 'adapters': adapters, 'registry': registry, 'audits': audits, 'reachability': reach}


def render(f: dict | None = None) -> str:
    f = facts() if f is None else f
    b = f['board']
    cohort = b['headline_counted_cohort']
    rules = f['rules']
    fitted = sorted(k for k, v in f['runtime']['receipts'].items() if v.get('status') == 'FITTED_RECEIPT')
    not_fitted = sorted(f['runtime']['not_fitted'])
    adapter_counts: dict[str, int] = {}
    for a in f['adapters'].values():
        adapter_counts[a.get('adapter_status', 'UNSPECIFIED')] = adapter_counts.get(a.get('adapter_status', 'UNSPECIFIED'), 0) + 1
    beaten = f['challenger']['acceptance']['sports_beaten']
    lines = [
        '# Current state',
        '',
        '> Generated by `python -B -m research.operations.current_state write`; do not edit by hand. `verify` fails when this page is stale.',
        '> Other documents state rules and history; this page alone states what is true now.',
        '',
        '## Authority',
        '',
        '| Item | Value |',
        '|---|---|',
        f'| Status | {f["status"]} |',
        f'| Method | {f["method"]} |',
        f'| Control revision | {f["control"]} |',
        f'| Scoring version | {f["scoring"]} |',
        f'| Active freeze | [{f["manifest"]}]({f["manifest"]}) |',
        f'| Next canonical ID (ledger-backed allocator) | **{f["next_id"]}** |',
        f'| Active Combined Log | `prediction logs/{f["log"]}` |',
        '| Mini-log format | `mini-log-3` (`mini-log-2` minis are still accepted) |',
        f'| Settlement register | kind `{f["pointer"]["kind"]}`, [{Path(f["pointer"]["manifest_path"]).parent.name}]({f["pointer"]["report_path"]}) |',
        '',
        '## Selection rules (provisional until the prospective window completes)',
        '',
        '- Only Rank 1 and Rank 2 count as wins (Rule T2); a Rank-1 loss gets a deep retrospection (Rule R1).',
        f'- p_card ceiling {rules["p_card_max"]:.0%}; Rank-1 gate p_card >= {rules["rank1_gate"]["p_min"]:.0%} and margin >= {rules["rank1_gate"]["margin_min"]:.0%}; '
        f'Rank 2 p_card >= {rules["rank2"]["p_min"]:.0%}; joint top-two failure warning above {rules["rank2"]["joint_failure_warn"]:.0%}.',
        f'- Source: `runtime/config/selection_rules.json` ({rules["status"].split(":")[0]}).',
        '',
        '## Scoreboard (counted cohort: Rank 1 and Rank 2, stable Rank-1 cards)',
        '',
        f'- Cards scored: {b["cards"]} ({b["first_id"]} to {b["last_id"]}); counted cohort {cohort["cards"]} cards, '
        f'{cohort["counted_wins"]} counted wins, win rate {cohort["counted_win_rate"]:.1%} (95% interval {cohort["counted_ci95"][0]:.1%} to {cohort["counted_ci95"][1]:.1%}).',
        '- The legacy history is informational only; nothing here is performance-certified. Source: `research/scoreboard/SCOREBOARD.md`.',
        '',
        '## Runtime models',
        '',
        f'- Rolling-origin receipts for the fitted engines: {", ".join(fitted)}. Not fitted for want of data: {", ".join(not_fitted)}.',
        f'- Boosted challenger acceptance (beats the baseline on winner log loss and total CRPS in at least two sports): '
        f'{"MET in " + ", ".join(beaten) if f["challenger"]["acceptance"]["met"] else "NOT MET"}.',
        '',
        '## Sources',
        '',
        f'- Executable registry: {len(f["registry"])} sources; adapter registry: ' + ', '.join(f'{n} {s}' for s, n in sorted(adapter_counts.items())) + '.',
        f'- Lineage audits on file: {len(f["audits"])}. Environments with a reachability observation: {", ".join(f["reachability"]) or "none"}.',
        '',
        '## Where things are',
        '',
        '| Need | Document |',
        '|---|---|',
        '| Rules | [CURRENT_RULES.md](CURRENT_RULES.md), [METHOD.md](METHOD.md) |',
        '| Operator prompts | [research/prompts/](research/prompts/README.md) |',
        '| Card and mini formats | [CARD_AND_LOG_TEMPLATES.md](CARD_AND_LOG_TEMPLATES.md) |',
        '| Retrospective and recommendation status | [FRAMEWORK_RETROSPECTIVE_2026-10-09.md](FRAMEWORK_RETROSPECTIVE_2026-10-09.md) |',
        '| Sources and reachability | [SOURCES.md](SOURCES.md) |',
        '| Superseded freezes | `archive/controls/` |',
        '',
    ]
    return '\n'.join(lines)


def stale_statements() -> list[str]:
    out = []
    for rel in LIVING_DOCS:
        path = ROOT / rel
        if not path.exists():
            continue
        for n, line in enumerate(path.read_text(encoding='utf-8').splitlines(), 1):
            if STALE.search(line):
                out.append(f'{rel}:{n}: {line.strip()[:120]}')
    return out


def verify() -> list[str]:
    problems = []
    if not OUT.exists():
        return ['CURRENT_STATE.md is missing']
    if OUT.read_text(encoding='utf-8').replace('\r\n', '\n') != render():
        problems.append('CURRENT_STATE.md differs from a fresh render; run `current_state write`')
    problems += [f'stale statement: {s}' for s in stale_statements()]
    return problems


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('cmd', choices=['write', 'verify'])
    args = parser.parse_args(argv)
    if args.cmd == 'write':
        OUT.write_text(render(), encoding='utf-8', newline='\n')
        print(f'wrote {OUT.name}')
        return 0
    problems = verify()
    print(json.dumps({'passed': not problems, 'problems': problems}, indent=1))
    return 1 if problems else 0


if __name__ == '__main__':
    sys.exit(main())
