"""Reachability matrix per environment (SRC-07).

The framework runs in two places that do not see the same internet: the local Windows machine where the prompts are used, and a cloud
container behind a proxy. A source that works in one can fail in the other (the cloud container, for example, cannot open a tunnel to most
sports hosts). The matrix records, per environment and per source, whether the registry's probe URL answered with the expected content,
and lists for each source the other registered sources of the same league on a different upstream lineage as fallbacks.

  python -B -m research.operations.reachability probe --env local_windows      # run weekly on each machine; writes research/reachability/<env>_<date>.json
  python -B -m research.operations.reachability render                          # prints the matrix (Markdown)
  python -B -m research.operations.reachability render --write SOURCES.md       # replaces the block between the REACHABILITY markers
  python -B -m research.operations.reachability verify                          # every observation file is well formed

A probe records accessibility and the registry's expected text only. It does not stand for exact-event truth or independent collection.
Observation files are append-only (a new dated file per probe); an environment with no file is shown as NOT_YET_PROBED.
"""
from __future__ import annotations
import argparse
import json
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[2]
REGISTRY = ROOT / 'research/sources_registry.json'
OBS_DIR = ROOT / 'research/reachability'
KNOWN_ENVIRONMENTS = ('local_windows', 'cloud_container')
STATUSES = ('EXPECTED_CONTENT', 'CONTENT_UNVERIFIED', 'UNAVAILABLE', 'MANUAL_OR_NO_PROBE')
BEGIN, END = '<!-- REACHABILITY-MATRIX:BEGIN (generated by research.operations.reachability) -->', '<!-- REACHABILITY-MATRIX:END -->'
_ENV = re.compile(r'^[a-z][a-z0-9_]*$')


def registry() -> dict:
    return json.loads(REGISTRY.read_text(encoding='utf-8'))['sources']


def probe_one(source_id: str, source: dict, timeout: int = 15) -> dict:
    url = source.get('probe_url')
    if source.get('access_mode') != 'AUTOMATED_ALLOWED' or not url:
        return {'status': 'MANUAL_OR_NO_PROBE', 'detail': str(source.get('access_mode'))}
    started = time.monotonic()
    try:
        with urlopen(Request(url, headers={'User-Agent': 'SportsResearch/2026.10 (reachability probe)'}), timeout=timeout) as reply:
            body = reply.read(2_000_000).decode('utf-8', errors='replace')
            code = reply.status
    except HTTPError as exc:
        return {'status': 'UNAVAILABLE', 'detail': f'HTTP {exc.code}', 'seconds': round(time.monotonic() - started, 2)}
    except (URLError, TimeoutError, OSError, ValueError) as exc:
        return {'status': 'UNAVAILABLE', 'detail': f'{type(exc).__name__}: {exc}'[:200], 'seconds': round(time.monotonic() - started, 2)}
    expected = source.get('probe_expected_text', [])
    ok = all(token in body for token in expected)
    return {'status': 'EXPECTED_CONTENT' if ok else 'CONTENT_UNVERIFIED', 'detail': f'HTTP {code}', 'seconds': round(time.monotonic() - started, 2)}


def probe(env: str, out_dir: Path = OBS_DIR, sources: dict | None = None, prober=probe_one) -> Path:
    if not _ENV.match(env):
        raise ValueError('environment name must be lowercase letters, digits or underscores')
    sources = registry() if sources is None else sources
    now = datetime.now(timezone.utc)
    result = {'schema': 'reachability-observation-1', 'environment': env, 'observed_utc': now.isoformat(),
              'scope': 'accessibility and the registry expected text only; not exact-event truth or independent collection',
              'sources': {sid: prober(sid, src) for sid, src in sorted(sources.items())}}
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{env}_{now.strftime('%Y-%m-%d')}.json"
    if path.exists():
        path = out_dir / f"{env}_{now.strftime('%Y-%m-%dT%H%M%SZ')}.json"
    with path.open('x', encoding='utf-8') as handle:
        json.dump(result, handle, indent=2, sort_keys=True)
        handle.write('\n')
    return path


def observations(out_dir: Path = OBS_DIR) -> dict[str, dict]:
    """Latest observation per environment."""
    latest: dict[str, dict] = {}
    for path in sorted(out_dir.glob('*.json')) if out_dir.exists() else []:
        obj = json.loads(path.read_text(encoding='utf-8'))
        env = obj['environment']
        if env not in latest or obj['observed_utc'] > latest[env]['observed_utc']:
            latest[env] = obj
    return latest


def fallbacks(sources: dict) -> dict[str, list[str]]:
    """For each source, the other automated sources that share a league and sit on a different upstream lineage."""
    out: dict[str, list[str]] = {}
    for sid, src in sources.items():
        mine = set(src.get('leagues', []))
        out[sid] = sorted(o for o, osrc in sources.items()
                          if o != sid and osrc.get('access_mode') == 'AUTOMATED_ALLOWED' and mine & set(osrc.get('leagues', []))
                          and osrc.get('upstream_lineage_id') != src.get('upstream_lineage_id'))
    return out


def render(sources: dict | None = None, obs: dict | None = None) -> str:
    sources = registry() if sources is None else sources
    obs = observations() if obs is None else obs
    envs = list(KNOWN_ENVIRONMENTS) + sorted(e for e in obs if e not in KNOWN_ENVIRONMENTS)
    fb = fallbacks(sources)
    head = ['Source', 'Leagues', *[f'{e} (observed)' for e in envs], 'Fallbacks (other lineage, same league)']
    lines = ['| ' + ' | '.join(head) + ' |', '|' + '---|' * len(head)]
    for sid, src in sorted(sources.items()):
        cells = []
        for env in envs:
            o = obs.get(env)
            if not o:
                cells.append('NOT_YET_PROBED')
            else:
                r = o['sources'].get(sid)
                cells.append(f"{r['status']} ({r['detail']}; {o['observed_utc'][:10]})" if r else f"NOT_IN_PROBE ({o['observed_utc'][:10]})")
        lines.append(f"| `{sid}` | {', '.join(src.get('leagues', [])) or '—'} | " + ' | '.join(cells) + f" | {', '.join(f'`{f}`' for f in fb[sid]) or 'none registered'} |")
    return '\n'.join(lines)


def write_block(path: Path, table: str) -> None:
    text = path.read_text(encoding='utf-8')
    block = f'{BEGIN}\n\n{table}\n\n{END}'
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        new = head + block + tail
    else:
        raise ValueError(f'{path} has no REACHABILITY-MATRIX markers')
    path.write_text(new, encoding='utf-8', newline='')


def verify(out_dir: Path = OBS_DIR) -> list[str]:
    problems = []
    for path in sorted(out_dir.glob('*.json')) if out_dir.exists() else []:
        try:
            obj = json.loads(path.read_text(encoding='utf-8'))
        except json.JSONDecodeError as exc:
            problems.append(f'{path.name}: {exc}')
            continue
        if obj.get('schema') != 'reachability-observation-1' or not _ENV.match(str(obj.get('environment', ''))):
            problems.append(f'{path.name}: wrong schema or environment')
            continue
        for sid, r in obj.get('sources', {}).items():
            if r.get('status') not in STATUSES:
                problems.append(f'{path.name}: {sid} has unknown status {r.get("status")!r}')
        if not path.name.startswith(obj['environment'] + '_'):
            problems.append(f'{path.name}: file name does not start with its environment')
    return problems


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest='cmd', required=True)
    p = sub.add_parser('probe')
    p.add_argument('--env', required=True)
    r = sub.add_parser('render')
    r.add_argument('--write', type=Path)
    sub.add_parser('verify')
    args = parser.parse_args(argv)
    if args.cmd == 'probe':
        path = probe(args.env)
        data = json.loads(path.read_text(encoding='utf-8'))
        print(json.dumps({k: v['status'] for k, v in data['sources'].items()}, indent=2))
        print(f'wrote {path.relative_to(ROOT).as_posix()}')
        return 0
    if args.cmd == 'render':
        table = render()
        if args.write:
            write_block(args.write, table)
            print(f'updated {args.write}')
        else:
            print(table)
        return 0
    problems = verify()
    print(json.dumps({'passed': not problems, 'problems': problems}, indent=1))
    return 0 if not problems else 1


if __name__ == '__main__':
    sys.exit(main())
