"""Quantitative regime flags estimated from the archive (PRD-07).

  python -B -m research.operations.regimes build    # write runtime/config/regimes.json and the BASE_RATES_REGISTER.md block
  python -B -m research.operations.regimes verify   # fail if either is stale

A regime flag on a card is only worth something if it moves the distribution by a measured amount. For every league and flag this
module reports the estimated multiplier on scoring, an interval from a season-block bootstrap (seasons are the exchangeable units:
games within a season share rules, rosters and officiating), and `recommended`: the multiplier engines may apply through
`scoring_multiplier`. When the interval contains 1 the recommendation is 1.0, because applying an unmeasured shift would be an
analyst nudge; the point estimate is still published.

Flags: FINALS_COMPRESSION (finals/playoffs against the same seasons' regular games), EARLY_SEASON (a team's first five games),
RULE_CHANGE:<name> (before/after seasons), CUP_ROTATION. A flag the archive cannot measure is reported NOT_ESTIMABLE with the
reason; nothing is invented for it.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np

from research.src import archive_std, h0_features

ROOT = Path(__file__).resolve().parents[2]
CONFIG = ROOT / 'runtime/config/regimes.json'
REGISTER = ROOT / 'BASE_RATES_REGISTER.md'
BEGIN, END = '<!-- BEGIN REGIMES (generated by research.operations.regimes) -->', '<!-- END REGIMES -->'
SCHEMA = 'regimes-1'
LEAGUES = [('Basketball', 'NBA'), ('Basketball', 'WNBA'), ('Ice Hockey', 'NHL'), ('Baseball', 'MLB'), ('Rugby League', 'NRL'),
           ('AFL', 'AFL'), ('American Football', 'NFL')]
RULE_CHANGES = {
    ('Rugby League', 'NRL'): {'name': 'six_again', 'effective_season': 2020, 'before': (2015, 2019), 'after': (2021, 2025),
                              'note': 'six-again ruling introduced from round 3 of 2020; 2020 itself is mixed and excluded'},
}
NOT_ESTIMABLE = {
    'RULE_CHANGE:kbl_foreign_player_2026_27': 'The rule takes effect in 2026-27 and the archive holds no game played under it.',
    'CUP_ROTATION': 'The archive has scores only; rotation needs the starting lineups of the match and of the preceding fixtures.',
}
BOOTSTRAP = 2000
RECENT_SEASONS = 25          # the modern era only: rules, pace and officiating change over a century


def _bootstrap_ratio(num_by_season: dict[int, list[float]], den_by_season: dict[int, list[float]], seed: int = 17) -> dict:
    seasons = sorted(set(num_by_season) & set(den_by_season))
    if len(seasons) < 4:
        return {'status': 'INSUFFICIENT_SEASONS', 'seasons': len(seasons)}
    rng = np.random.default_rng(seed)

    def ratio(chosen):
        n = np.concatenate([num_by_season[s] for s in chosen])
        d = np.concatenate([den_by_season[s] for s in chosen])
        return float(n.mean() / d.mean())

    point = ratio(seasons)
    boots = np.array([ratio([seasons[i] for i in rng.integers(0, len(seasons), len(seasons))]) for _ in range(BOOTSTRAP)])
    lo, hi = float(np.percentile(boots, 2.5)), float(np.percentile(boots, 97.5))
    significant = not (lo <= 1.0 <= hi)
    return {'status': 'ESTIMATED', 'estimate': round(point, 4), 'ci95': [round(lo, 4), round(hi, 4)], 'seasons': len(seasons),
            'n_numerator': int(sum(len(v) for v in num_by_season.values())), 'n_denominator': int(sum(len(v) for v in den_by_season.values())),
            'significant': significant, 'recommended': round(point, 4) if significant else 1.0}


def finals_compression(events: list[Any]) -> dict:
    fin, reg = defaultdict(list), defaultdict(list)
    for e in events:
        total = float(e.home_score + e.away_score)
        if e.stage == 'finals':
            fin[e.season_year].append(total)
        elif e.stage == 'regular':
            reg[e.season_year].append(total)
    result = _bootstrap_ratio(fin, reg)
    if result['status'] == 'ESTIMATED':
        margins_f = [abs(e.home_score - e.away_score) for e in events if e.stage == 'finals']
        margins_r = [abs(e.home_score - e.away_score) for e in events if e.stage == 'regular']
        result['abs_margin_ratio'] = round(float(np.mean(margins_f) / np.mean(margins_r)), 4)
    return result


def early_season(events: list[Any]) -> dict:
    """Total scoring in a team's first five games against the rest of the regular season (seasons are the bootstrap units)."""
    regular = [e for e in events if e.stage == 'regular']
    rows = h0_features.build_rows(regular)
    early: dict[Any, list[float]] = defaultdict(list)
    late: dict[Any, list[float]] = defaultdict(list)
    for r in rows:
        (early if r['is_early_season'] else late)[r['season']].append(float(r['home_score'] + r['away_score']))
    result = _bootstrap_ratio(early, late)
    if result['status'] == 'ESTIMATED':
        elo_ll: dict[Any, list[list[float]]] = defaultdict(lambda: [[], []])
        for r in rows:
            if r['home_score'] == r['away_score']:
                continue
            p = 1.0 / (1.0 + 10.0 ** (-r['elo_diff'] / 400.0))
            y = float(r['home_score'] > r['away_score'])
            loss = -(y * np.log(max(p, 1e-6)) + (1 - y) * np.log(max(1 - p, 1e-6)))
            elo_ll[r['season']][0 if r['is_early_season'] else 1].append(float(loss))
        diffs = [np.mean(v[0]) - np.mean(v[1]) for v in elo_ll.values() if v[0] and v[1]]
        result['elo_logloss_excess_early'] = round(float(np.mean(diffs)), 4) if diffs else None
    return result


def rule_change(events: list[Any], spec: dict) -> dict:
    regular = [e for e in events if e.stage == 'regular']
    b0, b1 = spec['before']
    a0, a1 = spec['after']
    before = {y: [float(e.home_score + e.away_score) for e in regular if e.season_year == y] for y in range(b0, b1 + 1)}
    after = {y: [float(e.home_score + e.away_score) for e in regular if e.season_year == y] for y in range(a0, a1 + 1)}
    before = {y: v for y, v in before.items() if v}
    after = {y: v for y, v in after.items() if v}
    if len(before) < 3 or len(after) < 3:
        return {'status': 'INSUFFICIENT_SEASONS', 'before_seasons': len(before), 'after_seasons': len(after)}
    rng = np.random.default_rng(23)
    bs, as_ = sorted(before), sorted(after)

    def ratio(b, a):
        return float(np.concatenate([after[s] for s in a]).mean() / np.concatenate([before[s] for s in b]).mean())

    point = ratio(bs, as_)
    boots = np.array([ratio([bs[i] for i in rng.integers(0, len(bs), len(bs))], [as_[i] for i in rng.integers(0, len(as_), len(as_))]) for _ in range(BOOTSTRAP)])
    lo, hi = float(np.percentile(boots, 2.5)), float(np.percentile(boots, 97.5))
    significant = not (lo <= 1.0 <= hi)
    return {'status': 'ESTIMATED', 'estimate': round(point, 4), 'ci95': [round(lo, 4), round(hi, 4)], 'before': spec['before'], 'after': spec['after'],
            'effective_season': spec['effective_season'], 'note': spec['note'], 'significant': significant, 'recommended': round(point, 4) if significant else 1.0}


def estimate(archive_root: Path = archive_std.ARCHIVE_ROOT) -> dict:
    leagues: dict[str, Any] = {}
    sources: dict[str, str] = {}
    for sport, competition in LEAGUES:
        events = list(archive_std.iter_events(archive_root, sport=sport, competition=competition))
        if not events:
            continue
        latest = max(e.season_year for e in events)
        events = [e for e in events if e.season_year > latest - RECENT_SEASONS]
        for path in sorted({e.origin_path for e in events}):
            sources[path] = hashlib.sha256((archive_root.parent / path).read_bytes()).hexdigest() if (archive_root.parent / path).exists() else 'MISSING'
        entry: dict[str, Any] = {'sport': sport, 'FINALS_COMPRESSION': finals_compression(events), 'EARLY_SEASON': early_season(events)}
        spec = RULE_CHANGES.get((sport, competition))
        if spec:
            entry[f"RULE_CHANGE:{spec['name']}"] = rule_change(events, spec)
        leagues[competition] = entry
    digest = hashlib.sha256('\n'.join(f'{k}:{v}' for k, v in sorted(sources.items())).encode()).hexdigest()
    return {'schema': SCHEMA, 'method': f'season-block bootstrap of a ratio of mean game totals over each league\'s last {RECENT_SEASONS} seasons; recommended = estimate only when the 95% interval excludes 1',
            'leagues': leagues, 'not_estimable': NOT_ESTIMABLE, 'archive_files': len(sources), 'archive_sha256': digest}


def render(data: dict) -> str:
    lines = [BEGIN, '', '### Regime flags (PRD-07)', '',
             'Multipliers on game totals, estimated from the archive with a season-block bootstrap; engines apply `recommended` through '
             '`scoring_multiplier`, which is 1.0 whenever the 95% interval contains 1. Generated: do not edit by hand.', '',
             '| League | Flag | Estimate | 95% CI | Seasons | Recommended |', '|---|---|---:|---|---:|---:|']
    for league, entry in sorted(data['leagues'].items()):
        for flag, body in sorted(entry.items()):
            if flag == 'sport' or not isinstance(body, dict):
                continue
            if body.get('status') == 'ESTIMATED':
                seasons = body['seasons'] if 'seasons' in body else f"{body['before'][1] - body['before'][0] + 1}+{body['after'][1] - body['after'][0] + 1}"
                lines.append(f"| {league} | {flag} | {body['estimate']:.3f} | {body['ci95'][0]:.3f}–{body['ci95'][1]:.3f} | {seasons} | {body['recommended']:.3f} |")
            else:
                lines.append(f"| {league} | {flag} | n/a | n/a | — | 1.000 ({body['status']}) |")
    lines += ['', 'Not estimable from the archive:', '']
    lines += [f'- `{k}`: {v}' for k, v in sorted(data['not_estimable'].items())]
    lines += ['', END]
    return '\n'.join(lines)


def splice(register_text: str, block: str) -> str:
    if BEGIN in register_text and END in register_text:
        head, rest = register_text.split(BEGIN, 1)
        tail = rest.split(END, 1)[1]
        return head + block + tail
    return register_text.rstrip('\n') + '\n\n' + block + '\n'


def build(archive_root: Path = archive_std.ARCHIVE_ROOT, config: Path = CONFIG, register: Path = REGISTER) -> dict:
    data = estimate(archive_root)
    config.write_text(json.dumps(data, indent=1, sort_keys=True, ensure_ascii=False) + '\n', encoding='utf-8', newline='\n')
    text = register.read_text(encoding='utf-8')
    crlf = '\r\n' in text
    updated = splice(text.replace('\r\n', '\n'), render(data))
    register.write_bytes((updated.replace('\n', '\r\n') if crlf else updated).encode('utf-8'))
    return data


def verify(config: Path = CONFIG, register: Path = REGISTER) -> list[str]:
    problems = []
    if not config.exists():
        return [f'{config} is missing; run `python -B -m research.operations.regimes build`']
    data = json.loads(config.read_text(encoding='utf-8'))
    if data.get('schema') != SCHEMA:
        problems.append('regimes.json has an unexpected schema')
    block = render(data)
    text = register.read_text(encoding='utf-8').replace('\r\n', '\n')
    if block not in text:
        problems.append('BASE_RATES_REGISTER.md regime block differs from regimes.json; run `regimes build`')
    for league, entry in data['leagues'].items():
        for flag, body in entry.items():
            if isinstance(body, dict) and body.get('status') == 'ESTIMATED':
                lo, hi = body['ci95']
                expect = body['estimate'] if not lo <= 1.0 <= hi else 1.0
                if abs(body['recommended'] - expect) > 1e-9 or body['significant'] != (not lo <= 1.0 <= hi):
                    problems.append(f'{league}/{flag}: recommended multiplier does not follow the interval rule')
    return problems


def multiplier(league: str, flag: str, config: Path = CONFIG) -> float:
    """The multiplier an engine may apply for a flag (1.0 when unmeasured or not significant)."""
    body = json.loads(Path(config).read_text(encoding='utf-8'))['leagues'].get(league, {}).get(flag)
    return float(body['recommended']) if isinstance(body, dict) and body.get('status') == 'ESTIMATED' else 1.0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('command', choices=['build', 'verify'])
    args = parser.parse_args(argv)
    if args.command == 'build':
        data = build()
        print(json.dumps({'leagues': sorted(data['leagues']), 'config': str(CONFIG)}, indent=1))
        return 0
    problems = verify()
    print(json.dumps({'passed': not problems, 'problems': problems}, indent=1))
    return 1 if problems else 0


if __name__ == '__main__':
    sys.exit(main())
