"""Tests for tools/mlb_model.py (C-MLB-SHADOW, added 2026-09-26). Offline: synthetic statsapi fixtures."""
import datetime as dt
import json
import math
import random
import sys
import tempfile
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import mlb_model as mm  # noqa: E402

TEAMS = {"Aces": 1.35, "Bats": 1.15, "Cards": 1.0, "Docks": 1.0, "Eels": 0.85, "Fins": 0.7}
VENUES = {"Aces": 11, "Bats": 12, "Cards": 13, "Docks": 14, "Eels": 15, "Fins": 16}
PARK = {11: 1.0, 12: 1.0, 13: 1.0, 14: 1.3, 15: 1.0, 16: 1.0}


def synth_schedule(n_days=90, seed=3):
    """A season where team strength and one hitter-friendly park are real, generated by a shared-gamma
    Poisson process so the model family is correct."""
    rng = random.Random(seed)
    names = list(TEAMS)
    dates, pk = [], 700000
    start = dt.date(2026, 4, 1)
    for i in range(n_days):
        d = (start + dt.timedelta(days=i)).isoformat()
        order = names[:]
        rng.shuffle(order)
        games = []
        for h, a in zip(order[0::2], order[1::2]):
            z = rng.gammavariate(7.0, 1 / 7.0)
            base = 4.45 * PARK[VENUES[h]] * z
            lam_h = base * TEAMS[h] / TEAMS[a] * 1.03
            lam_a = base * TEAMS[a] / TEAMS[h] * 0.97

            def pois(lam):
                L, k, p = math.exp(-lam), 0, 1.0
                while True:
                    p *= rng.random()
                    if p <= L:
                        return k
                    k += 1
            hr, ar = pois(lam_h), pois(lam_a)
            while hr == ar:  # completed games cannot tie
                hr += rng.random() < 0.52
                ar += hr == ar
            pk += 1
            games.append({"gamePk": pk, "officialDate": d,
                          "status": {"abstractGameState": "Final", "detailedState": "Final"},
                          "venue": {"id": VENUES[h]},
                          "teams": {"home": {"team": {"name": h}, "score": hr}, "away": {"team": {"name": a}, "score": ar}}})
        dates.append({"date": d, "games": games})
    return {"dates": dates}


def feed(pk, when="2026-07-01T23:05:00Z", official="2026-07-01", state="Preview", home="Aces", away="Fins",
         hid=501, aid=502, linescore=None):
    f = {"gameData": {"datetime": {"dateTime": when, "officialDate": official}, "status": {"abstractGameState": state},
                      "teams": {"home": {"name": home}, "away": {"name": away}}, "venue": {"id": VENUES[home]},
                      "probablePitchers": {"home": {"id": hid}, "away": {"id": aid}}},
         "liveData": {}}
    if linescore:
        f["liveData"]["linescore"] = linescore
    return f


def people(ip, r, hr, bb, k, gs):
    return {"stats": [{"splits": [{"stat": {"inningsPitched": ip, "runs": r, "earnedRuns": r, "homeRuns": hr,
                                             "baseOnBalls": bb, "hitByPitch": 1, "strikeOuts": k, "gamesStarted": gs}}]}]}


class Fixture(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.dir = Path(self.tmp.name)
        (self.dir / "schedule_2026.json").write_text(json.dumps(synth_schedule()), encoding="utf-8")
        (self.dir / "people_501.json").write_text(json.dumps(people("120.1", 30, 8, 25, 150, 21)), encoding="utf-8")
        (self.dir / "people_502.json").write_text(json.dumps(people("80.0", 60, 16, 40, 50, 16)), encoding="utf-8")
        self.src = mm.Source(str(self.dir))

    def tearDown(self):
        self.tmp.cleanup()


class Primitives(unittest.TestCase):
    def test_joint_is_a_distribution_with_the_right_means(self):
        j = mm.shared_gamma_joint(4.6, 4.2, 7.0, 40)
        self.assertAlmostEqual(sum(j.values()), 1.0, places=9)
        self.assertAlmostEqual(sum(h * p for (h, a), p in j.items()), 4.6, places=3)
        var_t = sum((h + a) ** 2 * p for (h, a), p in j.items()) - 8.8 ** 2
        self.assertAlmostEqual(var_t, 8.8 + 8.8 ** 2 / 7.0, delta=0.05)  # negative-binomial total

    def test_no_tie_and_query_identities(self):
        j = mm.no_tie(mm.shared_gamma_joint(4.6, 4.2, 7.0, 40))
        self.assertFalse(any(h == a for h, a in j))
        q = mm.queries(j, 8.0)
        self.assertAlmostEqual(q["p_over"] + q["p_push"] + q["p_under"], 1.0, places=9)
        self.assertLessEqual(q["p_home_m15"], q["p_home_win"])          # P(−1.5) ≤ P(win)
        self.assertGreaterEqual(1 - q["p_away_m15"], q["p_home_win"])   # P(home +1.5) ≥ P(home win)
        self.assertEqual(mm.queries(j, 8.5)["p_push"], 0.0)

    def test_grid_too_small_is_refused(self):
        with self.assertRaises(ValueError):
            mm.shared_gamma_joint(9.0, 9.0, 2.0, 10)

    def test_innings_notation(self):
        self.assertAlmostEqual(mm.ip_to_float("25.1"), 25 + 1 / 3)
        self.assertAlmostEqual(mm.ip_to_float("25.2"), 25 + 2 / 3)
        self.assertEqual(mm.ip_to_float("7"), 7)


class Model(Fixture):
    def test_leak_free_history(self):
        before = self.src.season_games(2026, "2026-05-01")
        self.assertTrue(before and all(g["date"] < "2026-05-01" for g in before))

    def test_ratings_recover_the_structure(self):
        rt = mm.Ratings(self.src.season_games(2026, "2026-07-01"))
        self.assertGreater(rt.off["Aces"], rt.off["Fins"])
        self.assertLess(rt.dfn["Aces"], rt.dfn["Fins"])
        self.assertGreater(rt.park[14], rt.park[11])       # the hitter-friendly park
        self.assertGreater(rt.home_f, rt.away_f)
        q = rt.predict("Aces", "Fins", 8.5)
        self.assertGreater(q["p_home_win"], 0.6)
        self.assertGreater(rt.predict("Docks", "Cards", 8.5)["mean_total"], rt.predict("Cards", "Docks", 8.5)["mean_total"])

    def test_starter_term_moves_the_opponent_only(self):
        rt = mm.Ratings(self.src.season_games(2026, "2026-07-01"))
        ace = self.src.pitcher(501, 2026, "2026-07-01")
        bad = self.src.pitcher(502, 2026, "2026-07-01")
        h0, a0_ = rt.means("Cards", "Docks", 13)
        h1, a1 = rt.means("Cards", "Docks", 13, home_sp=ace)
        self.assertAlmostEqual(h0, h1)            # the home starter does not change the home offence
        self.assertLess(a1, a0_)                  # a good home starter lowers the away scoring
        _, a2 = rt.means("Cards", "Docks", 13, home_sp=bad)
        self.assertGreater(a2, a0_)
        lo, hi = mm.PRIORS["starter_mult_bounds"]
        m = rt.starter_multiplier({"ip": 5.0, "r": 40, "hr": 9, "bb": 9, "hbp": 0, "k": 0, "gs": 1}, rt.m)
        self.assertLessEqual(m, hi)
        self.assertGreaterEqual(m, lo)

    def test_validate_is_rolling_origin_and_finds_real_signal(self):
        games = self.src.season_games(2026, "2026-12-31")
        res = mm.validate(games, min_prior=120, boot=200)
        self.assertGreater(res["n_games"], 100)
        self.assertLess(res["a1_minus_a0"], 0)  # synthetic teams really differ, so A1 must beat A0
        lo, hi = res["ci95_day_block"]
        self.assertLessEqual(lo, hi)


class Shadow(Fixture):
    def test_shadow_freezes_once_and_refuses_started_games(self):
        (self.dir / "feed_800001.json").write_text(json.dumps(feed(800001)), encoding="utf-8")
        log = self.dir / "shadow_log.csv"
        now = dt.datetime(2026, 7, 1, 20, 0, tzinfo=dt.timezone.utc)
        row = mm.shadow(self.src, 800001, 8.5, "P-600", now, log)
        self.assertEqual(row["card"], "P-600")
        self.assertEqual(int(row["n_prior_games"]), len(self.src.season_games(2026, "2026-07-01")))
        for pre in ("a1_", "a0_"):
            tot = sum(float(row[pre + k]) for k in ("p_over", "p_push", "p_under"))
            self.assertAlmostEqual(tot, 1.0, places=3)
        with self.assertRaises(SystemExit):   # never replaced
            mm.shadow(self.src, 800001, 8.5, "P-600", now, log)
        late = dt.datetime(2026, 7, 1, 23, 30, tzinfo=dt.timezone.utc)
        (self.dir / "feed_800002.json").write_text(json.dumps(feed(800002)), encoding="utf-8")
        with self.assertRaises(SystemExit):   # after first pitch
            mm.shadow(self.src, 800002, 8.5, "P-601", late, log)
        (self.dir / "feed_800003.json").write_text(json.dumps(feed(800003, state="Live")), encoding="utf-8")
        with self.assertRaises(SystemExit):   # feed says live
            mm.shadow(self.src, 800003, 8.5, "P-602", now, log)
        self.assertEqual(len(mm.read_rows(log)), 1)

    def test_settle_and_score(self):
        (self.dir / "feed_800001.json").write_text(json.dumps(feed(800001)), encoding="utf-8")
        log, results = self.dir / "shadow_log.csv", self.dir / "shadow_results.csv"
        now = dt.datetime(2026, 7, 1, 20, 0, tzinfo=dt.timezone.utc)
        mm.shadow(self.src, 800001, 8.5, "P-600", now, log)
        mm.shadow(self.src, 800001, 7.5, "P-600", now, log)            # a second line for the same game
        self.assertEqual(mm.settle(self.src, log, results, now), [])   # not final yet
        final = feed(800001, state="Final", linescore={"teams": {"home": {"runs": 6}, "away": {"runs": 2}},
                                                        "innings": [{}] * 9})
        (self.dir / "feed_800001.json").write_text(json.dumps(final), encoding="utf-8")
        added = mm.settle(self.src, log, results, now + dt.timedelta(hours=5))
        self.assertEqual(len(added), 1)
        self.assertEqual(mm.settle(self.src, log, results, now + dt.timedelta(hours=6)), [])  # append-only, once
        s = mm.score(log, results)
        self.assertEqual(s["home_win"]["n"], 1)                  # the game's side result counts once
        self.assertEqual(s["total_over"]["n"], 2)                 # each frozen total line counts


if __name__ == "__main__":
    unittest.main()
